### ISSUE TITLE
Token Refresh

### ISSUE THREAD

**Issue by ryanxedi** [dcblogdev/laravel-xero#1]
Kudos to you.  This is the easiest to implement Xero pacakge yet.

#Feature request
Add a RefreshToken function to silently update your token without having to sign back in every 60 days,

This would be handy top run as an artisan command on a cronjob.

**Comment by dcblogdev** [comment]
Thank you for sponsoring me! it's really appreciated!

The package internally does refresh the token when the token is about to expire, but having this done from a console command is a good idea, to support cases of inactivity from the user.

**Comment by saravanakumar2906** [comment]
post payment not working

**Comment by hirani89** [comment]
Hi @dcblogdev,

Thanks for making this open source.

Has the token refresh been implemented? Also, Is the webhook feature implemented? I do not see any documentation on that.

**Comment by tonypartridge** [comment]
bump, just checking if this has been implemented yet? Or if we should programatically write a cli script to auto login as a user and call a function once a day to cause a refresh?

**Comment by dcblogdev** [comment]
I've added a command to refresh the token

```
php artisan xero:keep-alive
```

This will refresh the token when its due to expire.
Its recommended to add this to a schedule ie inside `App\Console\Kernal.php` add the command to a schedule.

```php 
protected function schedule(Schedule $schedule)
{
    $schedule->command('xero:keep-alive')->everyFiveMinutes();
}
```

**Comment by tonypartridge** [comment]
Ahh nice, I had wrote my own method so that will be helpful!
