### ISSUE TITLE
Multi-Tenant Use

### ISSUE THREAD

**Issue by Childplan** [dcblogdev/laravel-xero#10]
Many thanks for you work on this package - this is one of the easiest Xero / Laravel integrations I have used.

I am trying to incorporate this package in a multi-tenant solution based on Laravel Spark but I am struggling to adapt the code when there is more than 1 Xero organisation in the XeroSettings table.  Any pointers on how to adapt the package fro that use case would be appreciated.

**Comment by dcblogdev** [comment]
Hi Chris, Looking at the package I can see it's only set up to get a single user, it needs changing to it can work with multiple users and then have an option to pass in a user_id or team_id to get an instance of a specific row.

I'll modify the package to support this, I'm away for the next few days. I'll work on this as soon as I get a chance.

**Comment by deanzod** [comment]
Yes this would be great if we could pass in a user `Xero::connect(auth()->user())` and have it create a token row per connection/user. Not sure how best to do this and also keep the ability to create a global single xero connection though

**Comment by tonypartridge** [comment]
Hi @dcblogdev just wondering how you got on? I have a use case where I want a single user to authenticate multiple new XERO 'Tenants'. Essentially they have multiple client accounts (tenants) under their Xero account.
So a row for each XERO tenant would make sense, with a parent identifier being the first connected tenant sense the tokens work for both?

**Comment by tonypartridge** [comment]
Looking at the codebase, you update always based on id = 1 or it creates it. When re-connecting you empty out the tokens table.

I would suggest update/create tokens based on the tenant_name and id = current_user_id, since it would also allow multiple tokens etc for 1 user id, maybe a XERO username or id store for the tokens?

And a cli command to allow refreshing tokens too?

**Comment by tonypartridge** [comment]
Ideally there should be a user_id column and ID is auto-incrementally too....

**Comment by Childplan** [comment]
Hi @dcblogdev - just wondering if you have had a chance to look at the changes required to make this package 'multi-tenant' capable.

To provide a bit more context for the solution I am trying to address.  My application is based on Laravel Spark, with Users linked to Teams, with a user potentially belonging to multiple Teams.  The application automates the loading of invoices created in Xero into the application.

I have a XeroSettings table, that holds the connection settings for each Team, along with other relevant information.  

When a User who has access to multiple Xero tenants connects to Xero, I pull back a list of all the potential tenants, and select the most recently connected tenant with the following code: 

$result = collect($result)->sortbyDESC('updatedDateUtc')->toArray();
(where $result = json_decode($response->getBody()->getContents(), true);)

All of this works fine, with multiple tenants connected, however the current package falls down when the token needs to be refreshed for different tenants.

**Comment by tonypartridge** [comment]
@Childplan did you see my PR, it's a work in progress. But with it, you can associate the ID from the tokens take with your users table or teams table, and then when loading a team or user get the id and pass it in. For example I use:

Xero::setTenantId(Auth::user()->currentTeam->xero_tid);

Then subsequent calls will fetch and then set the tenant's data.

**Comment by dcblogdev** [comment]
Apologies for the delay; I'll be looking over this tonight, the PR looks on the right track.

**Comment by tonypartridge** [comment]
@dcblogdev how are you getting on?

**Comment by tonypartridge** [comment]
Just wondering if this is something you are prepared to support? I can do a PR for a lot more of it. 

I'd ideally like to use the Crypt library on the token stores too and a refresh CLI command which I already have setup.

**Comment by dcblogdev** [comment]
Thanks for your PR @tonypartridge I've issued a new release now. Apologies it took so long for me to look at it.

I do want to continue support so yes please add your PR's

**Comment by Childplan** [comment]
Thanks David - this goes a long way to address the multi-tenant use.

It is worth noting that a single Xero user can have access to multiple Xero organisations.  To ensure that the latest Xero organisation is added to you application if the user has already added one then the following code can be added to the Xero.php replacing lines 110 - 120

> $result = json_decode($response->getBody()->getContents(), true);

>  // Sort the result so that the most recent organisation
>  $result = collect($result)->sortbyDESC('updatedDateUtc')->toArray();
>                   
>  foreach ($result as $tenant) {
>                         $tenantData = [
>                             'auth_event_id'     => $result[0]['authEventId'],
>                             'tenant_id'         => $result[0]['tenantId'],
>                             'tenant_type'       => $result[0]['tenantType'],
>                             'tenant_name'       => $result[0]['tenantName'],
>                             'created_date_utc'  => $result[0]['createdDateUtc'],
>                             'updated_date_utc'  => $result[0]['updatedDateUtc'],
>                         ];

Sorry I am not sure how to make a pull request to include this.
