### ISSUE TITLE
Unable to Refresh Token

### ISSUE THREAD

**Issue by Childplan** [dcblogdev/laravel-xero#12]
After successfully connecting to Xero and saving the connection details to xero_tokens table, any attempt to interact with Xero though the API, such as trying to get an invoice via the resource_id results in the following error:

Undefined array key "tenant_id"

It **_seems_** that the $tenantData is not being passed to storeToken function - but I cannot identify the issue.

Any help appreciated

**Comment by dcblogdev** [comment]
I've released v1.1.0 can you check if this works for you now?
