### ISSUE TITLE
Undefined array key "id_token"

### ISSUE THREAD

**Issue by emotec** [dcblogdev/laravel-xero#13]
When trying to create a new contact I am getting this error.
My site connects to Xero correctly and stores the token data in the database. 
![Screenshot from 2022-07-15 11-27-57](https://user-images.githubusercontent.com/2248835/179206385-8c9bbe7e-68c2-47fd-be68-ef70e20e506f.png)

**Comment by emotec** [comment]
the very simple Xero::get('contacts'); also falls over with the same error.

Xero::getTenantName(); works correctly!

**Comment by dcblogdev** [comment]
Thanks for raising this, I'll look into this and come back to you.

**Comment by emotec** [comment]
![image](https://user-images.githubusercontent.com/2248835/179549302-2341eff8-0005-42c2-9a04-1778cb63ef75.png)

getAccessToken() function
'invalid_grant' is returned from Xero ?

is the grant type wrong? 
'grant_type'    => 'refresh_token',

also this line
if ($token->expires <= $now) {

I cant find $token->expires anywhere in the code? 

If I take this 'if' statement out of the code then the API call works correctly.
So perhaps there is a problem with the token expiry check?

**Comment by emotec** [comment]
Also I have a very similar website using the same Xero API. This works perfectly.  The laravel-xero code is a little earlier though. Before the multitenancy additions.

**Comment by dcblogdev** [comment]
I've identified the issue I'll push up a fix.

**Comment by dcblogdev** [comment]
I've released v1.1.0 can you check if this works for you now?

**Comment by emotec** [comment]
Hi David

I'm now getting this msg
![image](https://user-images.githubusercontent.com/2248835/179700980-fca0c81c-e6b5-4496-a2dd-de0eebab74fb.png)

Also there are now 2 tokens in the database
![image](https://user-images.githubusercontent.com/2248835/179701429-50fe19b9-6ee1-4102-92c3-46c9f6a77836.png)
the first one is missing some data

![image](https://user-images.githubusercontent.com/2248835/179701730-f51a9a80-f0e0-4123-964a-1062f5509dc5.png)

if ($tenantData != null) {
            $data = array_merge($data, $tenantData);
}

Seems to be a repeated if statement here? Is that right?

thx
Mark

**Comment by dcblogdev** [comment]
that's a duplicate line, I'll remove it.

Can you clear out the 2 rows and re-connect

**Comment by emotec** [comment]
Hi David... that didnt make any difference unfortunately.
I deleted the token data from the database and commented out the repeated lines.

Same result... same error and 2 tokens

thx
Mark

**Comment by dcblogdev** [comment]
okay, I'll do further testing after work.

**Comment by emotec** [comment]
thx David!

**Comment by emotec** [comment]
Hi David
I removed the extra token in the database and chnaged the id of the remaining token from 3 to 1!... Now its working again.

**Comment by robinhoodxuk** [comment]
Hi, 

I am having the same issue, using multi tenant, and after a short time a new record is added to the database with ID of 1, again with missing tenant ID/Name etc.. only the tokens populated. 

Assuming it must be being created in storeToken but not sure why it's doing it, if you have any idea's would be appreciated! On first connect to Xero it works perfectly then about 20mins later it creates a second record.

Thanks
Robin
