### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by emotec** [dcblogdev/laravel-xero#14]
Hi David

I'm trying to use this command 'php artisan xero:keep-alive'
but I get the error message 

There are no commands defined in the "xero" namespace.

What am I missing?

thx
Mark

**Comment by dcblogdev** [comment]
have you updated to v1.1.1 you should see 

<img width="205" alt="CleanShot 2022-09-07 at 17 42 03@2x" src="https://user-images.githubusercontent.com/1018170/188933651-eea15dbb-2398-4287-9320-dc2fbe7bd9ae.png">

when running `php artisan`

**Comment by emotec** [comment]
ok thx David
I'll check what version I have

Mark

**Comment by TonyPartridgeR** [comment]
@dcblogdev so this works well for 1 token, but not multiples. I've got 4 tokens and only one seems to be updating looking at the timestamps. 

I'll try and investigate a fix.

**Comment by tonypartridge** [comment]
@dcblogdev I forgot to tag this. But this is resolved in #19
