### ISSUE TITLE
Encryption of tokens

### ISSUE THREAD

**Issue by tonypartridger** [dcblogdev/laravel-xero#21]
We should look to add support for encrypting the tokens within the DB. IF the DB is compromised they would have a short window to keep the tokens alive, so if we have a configure method 'Encrypt Tokens' and use the native hash method this would be beneficial towards additional security.

**Comment by TonyPartridgeR** [comment]
No worries, I just thought I'd put it here and when one of us gets time we can do it :-) 

Hopefully a new MBP? I got the M1 Pro Max recently, made dev insanely quick.

**Comment by dcblogdev** [comment]
Yes I've just left my job I had an M1 loved it!

Don't recall ever hearing the fans! Getting a new M1 next week or it could be an M2 I'm happy either way it's got 33GB ram which it's way more then I need!

**Comment by TonyPartridgeR** [comment]
Dreamy! Sounds similar to me tbh, I couldn't argue with the cost with 20% off. Pays for its self in a few months.

**Comment by dcblogdev** [comment]
Thankfully my new job is paying for it 😀

**Comment by TonyPartridgeR** [comment]
Lucky devil! Hope the new job goes well!

**Comment by dcblogdev** [comment]
Thanks 😀
