### ISSUE TITLE
ModifiedAfter filter doesn't work

### ISSUE THREAD

**Issue by Intellimatic** [dcblogdev/laravel-xero#26]
Hi, 

When I try to apply the Modified After filter, it still returns all records, i.e.

`  $xeroResponse = Xero::get('contacts', ['Modified After' => '2022-12-01T00:00:00']);` doesn't actually filter the contact list . I tried different date formats, but to no avail. 

Xero docs say that the filter is actually an HTTP header "If-Modified-Since", not sure how to set it in this package, though?

**Comment by Intellimatic** [comment]
Created [PR](https://github.com/dcblogdev/laravel-xero/pull/27) that sets the header if the option is set.

**Comment by tonypartridger** [comment]
@dcblogdev  any reason this was not merged?
