### ISSUE TITLE
Last insert id Contacts/Invoices

### ISSUE THREAD

**Issue by fazeelDQ** [dcblogdev/laravel-xero#28]
How can i get the contact id and invoices id once a data is stored. is this possible?

**Comment by Duncan-dev1** [comment]
Assign a variable to the result of the call e.g $xero_invoice = Xero::invoices()->store($data);if the api call is successful, $xero_invoice will be an array that includes the invoice_id

**Comment by fazeelDQ** [comment]
Thanks mate
