### ISSUE TITLE
Attempt to read property "access_token" on string

### ISSUE THREAD

**Issue by emotec** [dcblogdev/laravel-xero#29]
Hi David

Everything was going fine and then all of a sudden I'm getting this error everytime i try to access the Xero API.
**Attempt to read property "access_token" on string**
I have reset the App / reconnected everything but none of that helped.

Any ideas?
thx
Mark
![Screenshot from 2023-02-10 16-44-57](https://user-images.githubusercontent.com/2248835/218153576-87b1a32c-96d5-456e-a980-502e80088050.png)
![Screenshot from 2023-02-10 16-48-03](https://user-images.githubusercontent.com/2248835/218153675-f1e1f493-cd9d-4d09-a39b-75687a870dbc.png)

**Comment by emotec** [comment]
Hi Dave
the error seems to be in the Xero.php file
Line 147 
return $token->access_token;

$token is not an object at this point and is actually only the token as a string.

return $token 
seems to work ok

**Comment by dcblogdev** [comment]
thanks for pin pointing this, there's a function that returns an array whilst the model returns an object. When the array token is returned it was not being returned for usage.

I've applied a fix that corrects this now.
