### ISSUE TITLE
PHP7 does not support Union types

### ISSUE THREAD

**Issue by GerhardKotze** [dcblogdev/laravel-xero#30]
Hi Author, 

Please note the implementation of Union types is not supported in php7 (Support was added in php8 and up)
a)  on line 74 (public function connect(): RedirectResponse|Application|Redirector)
b) on line 125 (public function getTokenData(): XeroToken|null)

Another limitation is that mixed types cannot have default values:
c) on line 24 (protected mixed $tenant_id = 0;)

Posible solutions
1) update script to be backwards compatible for php7 or
2) add php8 as a package dependency for version 1.1.4 and up

**Comment by tonypartridger** [comment]
Given the package now using Laravel 10 whereby php 8.1 is required theres no need to update the requirement to be php8?
