### ISSUE TITLE
Connect to Xero API silently?

### ISSUE THREAD

**Issue by rigorcadiz** [dcblogdev/laravel-xero#34]
Hi there, 

I'm trying to use the Xero API with my Laravel app and I find this package interesting and I'm totally new to Xero API. I watched your video and tried to read also here https://dcblog.dev/docs/laravel-xero/v1/introduction.

In your video, when connecting first time it shows that it gets redirected to https://authorize.xero.com. Is that really necessary for connecting to APIs in Xero? Is there anyway to connect without user interaction using this package? 

Thanks.

**Comment by dcblogdev** [comment]
Hi I'm afraid it does need to redirect to Xero its part of their oAuth flow see https://developer.xero.com/documentation/guides/oauth2/overview/ 

This is a one-time action one connected a refresh token is used to update a token when needed using https://github.com/dcblogdev/laravel-xero#refresh-token

**Comment by rigorcadiz** [comment]
> Hi I'm afraid it does need to redirect to Xero its part of their oAuth flow see https://developer.xero.com/documentation/guides/oauth2/overview/
> 
> This is a one-time action one connected a refresh token is used to update a token when needed using https://github.com/dcblogdev/laravel-xero#refresh-token

Alright. Yeah it seems like it's the only way. 

I'm not quite sure how their token works, is the one-time authorization is for the whole app as long as the token gets renewed or it's per session? I mean, if for example my backend is going to create invoices and connect to Xero API for every user that process purchase through stripe. Do I just reuse the existing token or every user needs to get the authorization? Thanks

**Comment by dcblogdev** [comment]
It would be the same token for all users of your application or one token for each tenant if using multi tenency
