### ISSUE TITLE
Fail when more than one connected Xero Org.

### ISSUE THREAD

**Issue by helloadmin** [dcblogdev/laravel-xero#43]
I'm using the following code: 
        Xero::setTenantId($tenant_id);
        dump(Xero::getTenantName());
        dump(Xero::contacts()->get());
        dump(Xero::invoices()->get());

When there is only one connected tenant and only one entry in the xero_tokens table, it works well.

When I connect to another Xero org and an additional row is added to the xero_tokens table and use setTenantId to specified the tenant_id found in the xero_tokens table,  it fails.  getTenantName() comes back with 'Attempt to read property"tenant_name" on null' but the first connect tenant still works.

**Note: for those having connection issues,  check the xero_tokens table, truncate it and reconnect to Xero with Xero::connect();**

ps.  Awesome code.  Thanks for putting this together, and the documentation and the Youtube vids.  It got me through the first couple steps with a lot less frustration.  kudos!.

**Comment by tonypartridge** [comment]
Are you still getting an issue?

**Comment by tonypartridger** [comment]
Closing as no response.
