### ISSUE TITLE
XeroAuthenticated is not recognizing within the server environment | I am using it under nginx

### ISSUE THREAD

**Issue by fazeelDQ** [dcblogdev/laravel-xero#44]
I have been trying to get the xero token and the connection established, I keep getting a 500 internal server error whenever i run the xero commands it's like this package is never installed. Can you please guide me on this?

**Comment by tonypartridge** [comment]
Did you resolve this? 
What do the debug logs say?

**Comment by tonypartridger** [comment]
Closing as no response.
