### ISSUE TITLE
![image](https://user-images.githubusercontent.com/2248835/179549302-2341eff8-0005-42c2-9a04-1778cb63ef75.png)

### ISSUE THREAD

**Issue by mattglover11** [dcblogdev/laravel-xero#45]
![image](https://user-images.githubusercontent.com/2248835/179549302-2341eff8-0005-42c2-9a04-1778cb63ef75.png)

getAccessToken() function
'invalid_grant' is returned from Xero ?

is the grant type wrong? 
'grant_type'    => 'refresh_token',

also this line
if ($token->expires <= $now) {

I cant find $token->expires anywhere in the code? 

If I take this 'if' statement out of the code then the API call works correctly.
So perhaps there is a problem with the token expiry check?

_Originally posted by @emotec in https://github.com/dcblogdev/laravel-xero/issues/13#issuecomment-1187668670_

**Comment by mattglover11** [comment]
getAccessToken

if ($token->expires <= $now) 

I think this should be expires_in ?


in getTokenData

you have         

if ($this->tenant_id) {
            return XeroToken::where('tenant_id', '=', $this->tenant_id)->first();
}

But $this->tenant_id returns the ID number from the xero_tokens table, not the xero tenant id - hence it never returns a token.

should it possibly be             return XeroToken::where('id', '=', $this->tenant_id)->first();
??

**Comment by mattglover11** [comment]
Here is my suggestion for an updated renewExpiringToken:

    public function renewExpiringToken($token)
    {

        $params = [
            'grant_type'    => 'refresh_token',
            'refresh_token' => $token->refresh_token,
            'redirect_uri'  => config('xero.redirectUri')
        ];

        $resultCode = $this->dopost(self::$tokenUrl, $params);
        
        // potential failure point if xero client id or secret id's have changed. Xero will return invalid_grant error.
        if (array_key_exists('error', $resultCode)) {
            $errorMessage = "Dcblogdev\Xero@renewExpiringToken: " . $resultCode['error'];
            if ($resultCode['error'] == "invalid_grant") {
                $errorMessage .= ". Has your XERO_CLIENT_ID or XERO_CLIENT_SECRET changed?";
            }
            throw new Exception("Dcblogdev\Xero@renewExpiringToken: " . $errorMessage);
        }

        $this->storeToken($resultCode, ['tenant_id' => $token->tenant_id]);

        return $resultCode['access_token'];
    }

**Comment by tonypartridger** [comment]
We have updated this in the doPost request. WE check the status code is 200, else throw an exception with some details.
