### ISSUE TITLE
Urgent Issue: No Error Message return when storing invoices failed.

### ISSUE THREAD

**Issue by marklester-cymra** [dcblogdev/laravel-xero#52]
Creeating invoice works fine, but suddenly, something went wrong with creating one, i try looking at my logs, but it only returns "" empty string which is useless.

**Comment by tonypartridge** [comment]
Can you dig down further? Where does it show it in your logs? I would advise installing Sentry and monitoring it since it will catch the exceptions for you.

**Comment by marklester-cymra** [comment]
> Can you dig down further? Where does it show it in your logs? I would advise installing Sentry and monitoring it since it will catch the exceptions for you.

![image](https://github.com/dcblogdev/laravel-xero/assets/141701888/a1a7ac6d-8eee-4526-a36b-f565c124e6b5)

I use laravel log viewer and try catch statement to catch the error, but it only shows "" empty srting. This also happens for sending invoices. I suggest to also catch the validation messages from the Xero

**Comment by marklester-cymra** [comment]
My code looks like this.
```

       if (isset($order->customer->meta->xero_contact_id)) {
                                    $xeroInvoice = Xero::invoices()->store([
                                        'Type' => 'ACCREC',
                                        'Status' => $hasZeroStock ? 'DRAFT': 'AUTHORISED',
                                        'Contact' => [
                                            'ContactID' => $order->customer->meta->xero_contact_id,
                                        ],
                                        'LineItems' => $lineItems ?? [],
                                        'Date' => Carbon::now('Australia/Sydney')->format('Y-m-d'),
                                        'DueDate' => Carbon::now('Australia/Sydney')->addDays(30)->format('Y-m-d'),
                                    ]);
                                    sleep(1);

                                    XeroInvoice::create([
                                        'xero_id' => $xeroInvoice['InvoiceID'],
                                        'number' => $xeroInvoice['InvoiceNumber'],
                                        'order_id' => $order->id,
                                        'status' => $xeroInvoice['Status'],
                                    ]);

                                    $order->update([
                                        'status' => 'order-invoiced',
                                    ]);
                                }
                            } catch (Exception $e) {
                                Mail::to(config('mail.to_support'))->bcc(explode(',', config('mail.bcc_emails')))->send(new ErrorMail($e));
                                $this->info('Caught exception: ',  $e->getMessage(), "\n");
                                Log::error('Xero Sync Invoice: Order #' . $order->reference . "\n" . $e->getMessage());
                            }
```
And the error line in 'DueDate' attribute, the package only return "" empty string.

**Comment by marklester-cymra** [comment]
> Can you dig down further? Where does it show it in your logs? I would advise installing Sentry and monitoring it since it will catch the exceptions for you.

This is the error I get. No Error message thrown.
![Screenshot 2024-02-27 083436](https://github.com/dcblogdev/laravel-xero/assets/141701888/e43404b9-0b03-4c44-ad8c-08a7730716eb)


And this is my code and it is pointing on DueDate line.
![Screenshot 2024-02-27 083548](https://github.com/dcblogdev/laravel-xero/assets/141701888/fde991c1-85e9-4b8a-bf8d-b4806d860a26)


Already contacted Xero, the issue is in the package. Because it only sends invoice on a specific time

**Comment by marklester-cymra** [comment]
I have this in Job that runs every 5 minutes. Its weird because invoices generated successfully w/o any errors every 12:30PM onwards in Australia. So in our case  we need to wait every 12:30PM for the invoice to be generated.

**Comment by tonypartridge** [comment]
I have a feeling you maybe running out of API requests if you have so many going on since XERO has quite tight limitations per day. Xero is funny how it returns its request. I'll try to put a catching into the request handler

**Comment by tonypartridge** [comment]
@marklester-cymra can you confirm this is because you didn't enable token refreshing / keep-alive?
