### ISSUE TITLE
Multitenant

### ISSUE THREAD

**Issue by stoneshaq** [dcblogdev/laravel-xero#6]
Hi David. Great package. i would like to use it for my multitenant app. What would be the best approach to get Client ID, Client Secret , etc from Database. Thanks for your time

**Comment by dcblogdev** [comment]
Thanks! You could override the config value when you have the credentials maybe in a controller or middleware

```php
config()->set(['xero.clientId' => 'the-value']);
config()->set(['xero.clientSecret' => 'the-value']);
config()->set(['xero.redirectUri' => 'the-value']);
```
