### ISSUE TITLE
Type issue on Keep Alive artisan command

### ISSUE THREAD

**Issue by johntrickett86** [dcblogdev/laravel-xero#64]
When running the artisan command:

`php artisan xero:keep-alive`

the following Type Error is received:

`Carbon\Carbon::rawAddUnit(): Argument #3 ($value) must be of type int|float, string given, called in /vendor/nesbot/carbon/src/Carbon/Traits/Units.php on line 356`

**Comment by johntrickett86** [comment]
I have opened a PR for this issue: TypeError on Keep Alive artisan command #63

**Comment by dcblogdev** [comment]
Good call, thank you.
