### ISSUE TITLE
Laravel 11 connection error

### ISSUE THREAD

**Issue by bluestormdesign** [dcblogdev/laravel-xero#65]
Running php artisan xero:keep-alive returns the following error:

TypeError Carbon\Carbon::rawAddUnit(): Argument #3 ($value) must be of type int|float, string given, called in /vendor/nesbot/carbon/src/Carbon/Traits/Units.php on line 356

Fix need in dcblogdev/laravel-xero/src/Models/XeroToken.php

Please update line 18 - 20

From:

return Attribute::get(
    fn(): DateTimeInterface => $this->updated_at->addSeconds($this->expires_in)
);

To:

return Attribute::get(
    fn(): DateTimeInterface => $this->updated_at->addSeconds((int)$this->expires_in)
);

**Comment by dcblogdev** [comment]
thanks for raising this and the PR, its now been added to the latest release

https://github.com/dcblogdev/laravel-xero/releases/tag/v1.1.10
