### ISSUE TITLE
refresh_token too long for field

### ISSUE THREAD

**Issue by Feng-Shui** [dcblogdev/laravel-xero#72]
I get the following error after authentication when sent back to the redirect URL:

`Data too long for column 'refresh_token'`

The token is 256 characters long and the field is a var_char(255).  Setting this field to text in the migration resolves the issue, I can successfully refresh with the token too.

Would you like a MR with this change?

**Comment by dcblogdev** [comment]
hmm there is already a migration:

```
Schema::table('xero_tokens', function (Blueprint $table) {
    $table->text('refresh_token')->change();
});
```
