### ISSUE TITLE
Docs have 404 error

### ISSUE THREAD

**Issue by andrewdrake** [dcblogdev/laravel-xero#8]
Great little package we are using in a project, however your docs have a 404 error since you moved your site - https://dcblog.dev/docs/laravel-xero

**Comment by dcblogdev** [comment]
Thanks I've moved most of the docs I've still got a few package docs to move, this one included I will get that moved on tonight.

**Comment by dcblogdev** [comment]
I've managed to get this done now. The docs are in the read me, I'll need to add some quick links to help move around but they are there now.
